# Generated by Django 5.1.6 on 2025-02-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='url',
        ),
        migrations.AddField(
            model_name='sound',
            name='sound_file',
            field=models.FileField(default='sounds/default.mp3', upload_to='sounds/'),
        ),
    ]
