# Generated by Django 5.1.6 on 2025-03-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_useractivitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='link_invite',
            new_name='code_invite',
        ),
    ]
