# Generated by Django 5.1.6 on 2025-03-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_link_invite_room_code_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='is_out',
            field=models.BooleanField(default=False),
        ),
    ]
