# Generated by Django 5.1.6 on 2025-03-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_roomparticipant_is_approved_roomparticipant_is_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundvideo',
            name='url',
        ),
        migrations.AddField(
            model_name='backgroundvideo',
            name='youtube_code',
            field=models.CharField(default='vcf', max_length=255),
            preserve_default=False,
        ),
    ]
