# Generated by Django 5.1.6 on 2025-03-09 20:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_roomcategory_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='room',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail'),
        ),
    ]
