# Generated by Django 5.1.6 on 2025-03-09 20:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_roomcategory_thumbnail_room_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundvideo',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
