# Generated by Django 5.1.6 on 2025-03-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_dailystudyrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailystudyrecord',
            unique_together={('user', 'date')},
        ),
    ]
