# Generated by Django 5.1.6 on 2025-03-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_dailystudyrecord_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailystudyrecord',
            unique_together=set(),
        ),
    ]
