# Generated by Django 5.1.6 on 2025-03-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_studysession_delete_dailystudyrecord'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studysession',
            table=None,
        ),
    ]
