# Generated by Django 5.1.6 on 2025-03-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_studysession_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='date',
            field=models.DateField(),
        ),
    ]
