# Generated by Django 5.1.6 on 2025-03-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_studysession_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='start_time',
        ),
    ]
