# Generated by Django 5.1.6 on 2025-03-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_studysession_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundvideo',
            name='youtube_code',
        ),
        migrations.AddField(
            model_name='backgroundvideo',
            name='youtube_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=zCefVNFwzUQ'),
            preserve_default=False,
        ),
    ]
