# Generated by Django 5.1.6 on 2025-03-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_backgroundvideo_youtube_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomparticipant',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('MODERATOR', 'Moderator')], default='USER', max_length=10),
        ),
    ]
