# Generated by Django 5.1.6 on 2025-03-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_backgroundvideo_youtube_code_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_level',
            field=models.CharField(choices=[('MEMBER', 'Member (0-10m)'), ('ENTRY', 'Entry (10m-60m)'), ('BEGINNER', 'Beginner (1-3h)'), ('INTERMEDIATE', 'Intermediate (3-6h)'), ('PROFICIENT', 'Proficient (6-10h)'), ('ADVANCED', 'Advanced (10-20h)'), ('EXPERT', 'Expert (20-40h)'), ('A_PLUS_STUDENT', 'A+ Student (40-60h)'), ('MASTER', 'Master (60-80h)'), ('GRANDMASTER', 'Grandmaster (80-140h)'), ('STUDY_MACHINE', 'Study-Machine (140-200h)'), ('STUDY_MASTER', 'Study Master (200+h)')], default='MEMBER', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_study_time',
            field=models.FloatField(default=0),
        ),
    ]
