# Generated by Django 5.1.6 on 2025-03-22 14:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_user_managers_user_monthly_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail'),
        ),
    ]
