# Generated by Django 5.1.6 on 2025-03-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_roomparticipant_is_admin_roomparticipant_role'),
        ('api', '0027_alter_user_username'),
    ]

    operations = [
    ]
