# Generated by Django 5.1.6 on 2025-04-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userfavoritevideo_created_at_userfavoritevideo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritevideo',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userfavoritevideo',
            name='author_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='userfavoritevideo',
            name='youtube_url',
            field=models.URLField(unique=True),
        ),
    ]
