# Generated by Django 5.1.6 on 2025-04-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userfavoritevideo_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritevideo',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
