# Generated by Django 5.1.6 on 2025-04-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userfavoritevideo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritevideo',
            name='youtube_url',
            field=models.URLField(),
        ),
        migrations.AddConstraint(
            model_name='userfavoritevideo',
            constraint=models.UniqueConstraint(fields=('user', 'youtube_url'), name='unique_user_youtube_url'),
        ),
    ]
